version: "3"

services:
  app:
    image: "evseny/devops-for-programmers-project-74"
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm run test'
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: