version: "2"

services:
  app:
    image: "evseny/devops-for-programmers-project-74"
    build:
      context: .
      dockerfile: Docker.production
    command: bash -c 'sleep 3 && npm run test'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always