version: "2"

services:
  app:
    image: "evseny/devops-for-programmers-project-74"
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - ./config/.env.ci
    command: bash -c 'sleep 3 && npm run test'
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: