name: app image delivery
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create .env
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> app/.env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> app/.env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> app/.env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> app/.env

      - name: test the app
        run: make compose-ci

      - name: build the app image
        run: make compose-build

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push the app image
        run: make compose-push